# Generated by Django 4.2.9 on 2024-07-09 19:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название велосипеда')),
                ('description', models.TextField(max_length=550, null=True, verbose_name='Описание велосипеда')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5, message='Укажите стоимость аренды'), django.core.validators.MaxValueValidator(500, message='Слишком дорого, проверьте цену')], verbose_name='Стоимость аренды')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='RentedBicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rented', 'Арендован'), ('returned', 'Возвращен'), ('damaged', 'Велосипед поврежден или не возвращен вовремя')], default='rented', max_length=200, verbose_name='Статус')),
                ('rented_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда арендован')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда возвращен')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_bicycle', to='bicycles.bicycle', verbose_name='арендованный велосипед')),
            ],
            options={
                'verbose_name': 'Арендованный велосипед',
                'verbose_name_plural': 'Арендованные велосипеды',
            },
        ),
    ]
