# Generated by Django 4.2.9 on 2024-07-09 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedbicycle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='rental_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle', to='bicycles.pricetype', verbose_name='стоимость аренды'),
        ),
    ]
