# Generated by Django 4.2.9 on 2024-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='status',
            field=models.CharField(choices=[('availible', 'Доступен'), ('rented', 'Арендован'), ('notavailible', 'Недоступен по какой-то причине')], default='availible', max_length=200, verbose_name='Статус'),
        ),
    ]
