# Generated by Django 4.2.9 on 2024-07-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0003_bicycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedbicycle',
            name='final_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Получившаяся сумма'),
        ),
    ]
