# Generated by Django 4.2.9 on 2024-07-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0004_rentedbicycle_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedbicycle',
            name='final_price',
        ),
    ]
